pipeline {
	agent any 
	tools {
        maven 'Maven 3.9.0'
        jdk 'jdk13'
    }
	stages{
		stage("Compile"){
			steps{
				sh 'mvn compile'
			}
		}
		stage("Test"){
			steps{
				sh 'mvn test'
			}
		}
		stage("Build"){
			steps{
				sh 'mvn clean install'
			}
		}
	}
}